trigger:
  tags:
    include:
    - v*

pr: none

variables:
  #ACR
  dockerRegistryServiceConnection: 'ACRConnection'
  imageRepository: 'fcg-games'
  containerRegistry: 'fiapcloudgamesregistry.azurecr.io'
  dockerfilePath: 'src/FCG_Games.API/Dockerfile'

  #AKS
  azureSubscriptionConnection: 'AzureSubscriptionConnection'
  resourceGroupName: 'FCG'
  aksClusterName: 'fcg-cluster'
  k8sNamespace: 'default'

pool:
  name: 'Default'

stages:
- stage: Build_and_Push_Docker_Image
  displayName: '1. Build and Push Docker Image'
  jobs:
  - job: DockerJob
    displayName: 'Docker Build and Push to ACR'
    steps:
    - task: Docker@2
      displayName: 'Build and Push to ACR'
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(Build.SourceBranchName)
          latest

- stage: Deploy_to_AKS
  displayName: '2. Deploy to AKS'
  dependsOn: Build_and_Push_Docker_Image
  jobs:
  - job: DeployJob
    displayName: 'Deploy to AKS Cluster'
    steps:
    - script: |
        cat <<EOF> $(System.DefaultWorkingDirectory)/k8s/secrets.yaml
        apiVersion: v1
        kind: Secret
        metadata:
          name: fcg-games-secrets
        type: Opaque
        data:
          ConnectionStrings__DefaultConnection: "$(DbConnectionString)"
          Elasticsearch__ApiKey: "$(Elasticsearch__ApiKey)"
          Jwt__Key: "$(Jwt__Key)"
          RabbitMQ__Username: "$(RabbitMQ__Username)"
          RabbitMQ__Password: "$(RabbitMQ__Password)"
        EOF

    - task: KubernetesManifest@1
      displayName: 'Deploy to Kubernetes Cluster'
      inputs:
        action: 'deploy'
        connectionType: 'azureResourceManager'
        azureSubscriptionConnection: $(azureSubscriptionConnection)
        azureResourceGroup: $(resourceGroupName)
        kubernetesCluster: $(aksClusterName)
        namespace: $(k8sNamespace)
        manifests: |
          $(System.DefaultWorkingDirectory)/k8s/configmap.yaml
          $(System.DefaultWorkingDirectory)/k8s/secrets.yaml
          $(System.DefaultWorkingDirectory)/k8s/deployment.yaml
          $(System.DefaultWorkingDirectory)/k8s/service.yaml
          $(System.DefaultWorkingDirectory)/k8s/hpa.yaml
        containers: '$(containerRegistry)/$(imageRepository):$(Build.SourceBranchName)'